kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet restore
      - dotnet build

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet test

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet publish -c Release -o ./publish

trigger:
  event:
    - push
    - pull_request
