kind: pipeline
type: exec
name: default

steps:
- name: build
  environment:
    PAT:
      from_secret: PAT
  commands:
  - docker build -t dotnet-clean:1.0.0 .
  
trigger:
  event:
    include:
    - push
  branch:
  - main
