kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: build-docker
  image: drone/docker:latest
  commands:
  - docker build -t localhost:5000/dotnet-test:3.0.0 .
  - docker push localhost:5000/dotnet-test:3.0.0
