kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64
  
steps:
- name: build-docker
  environment:
    PASSWORD:
      from_secret: docker_pass
  commands:
  - echo $env:PASSWORD
  - Write-Output "Start of Script"
  - Write-Output $env:PASSWORD
  - Write-Output "End of Script"
  - echo $env:PASSWORD | docker login registry:5000 --username refactory --password-stdin
  - docker build -t registry:5000/dotnet-test .
  - docker push registry:5000/dotnet-test
