kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: build-docker
  commands:
  - docker build -t registry:5000/dotnet-test:4.0.0 .
  - docker push registry:5000/dotnet-test:4.0.0
