kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:20
  commands:
  - docker build -t dotnet-test -f ./Dockerfile .

trigger:
  event:
    include:
    - push
  branch:
  - main

