kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:20
  environment:
    PAT:
      from_secret: PAT
  commands:
  - echo $PAT
  - docker build dotnet-test .
  when:
    event: 
      - tag
