kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64
  
steps:
- name: build-docker
  commands:
  - docker build -t localhost:5000/dotnet-test:1.0.2 .
  - docker tag localhost:5000/dotnet-test:1.0.2 dotnet-test:1.0.2 
  - docker push localhost:5000/dotnet-test:1.0.2
  - docker push dotnet-test:1.0.2
