kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64
  
steps:
- name: build-docker
  commands:
  - docker build -t host.docker.internal:5000/dotnet-test:1.0.5 .
  - docker push host.docker.internal:5000/dotnet-test:1.0.5
