kind: pipeline
type: docker
name: default

platform:
    os: linux
    arch: amd64

volumes:
  - name: dockersock
    path: /var/run

steps:
  - name: build-docker
    image: docker:dind
    commands:
    - docker build -t registry/dotnet-test:1.0.5 .
    - docker push registry/dotnet-test:1.0.5
