kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: build-docker
  environment:
    PASSWORD:
      from_secret: docker_pass
  commands:
  - docker build -t registry:5001/dotnet-test .
  - docker push registry:5001/dotnet-test
